### Exercise: Week 7 & 8

#### DSC 540

Taniya Adhikari 02/07/2020

In [643]:
from bs4 import BeautifulSoup as BS
import pandas as pd

import numpy as np 
import matplotlib.pyplot as plt 
%matplotlib inlinexlsx

In [745]:
df = pd.read_csv('candyhierarchy2017.csv',encoding = "ISO-8859-1")

In [746]:
df.shape

(2460, 120)

In [747]:
df.head(3)

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**1. Handling Missing Data**

We will check which columns have the most missing data. If there are columns with more than 60% of the data missing, we will manually delete those

In [748]:
# check for missing value for Each column
def percentMissing(df):
    
    df_numeric = df.select_dtypes(include=[np.number])
    numeric_cols = df_numeric.columns.values
    print(numeric_cols)
    
    # % of missing data
    for col in df.columns:
        # create missing indicator for features with missing data
        missing = df[col].isnull()   # checking null value for each col
        pct_missing = np.mean(missing)*100
        print('{} - {}%'.format(col, round(pct_missing)))

In [749]:
# check for missing value for Each column
def percentMissing_Col(df):
    
    df_numeric = df.select_dtypes(include=[np.number])
    numeric_cols = df_numeric.columns.values
    print(numeric_cols)
    
    # % of missing data
    for col in df.columns:
        # create missing indicator for features with missing data
        missing = df[col].isnull()   # checking null value for each col
        pct_missing = np.mean(missing)*100
        if pct_missing >=60:
            print('{} - {}%'.format(col, round(pct_missing)))

In [750]:
percentMissing_Col(df)

['Internal ID' 'Q12: MEDIA [Daily Dish]' 'Q12: MEDIA [Science]'
 'Q12: MEDIA [ESPN]' 'Q12: MEDIA [Yahoo]']
Q7: JOY OTHER - 63%
Q8: DESPAIR OTHER - 71%
Q9: OTHER COMMENTS - 84%
Unnamed: 113 - 100%
Q12: MEDIA [Daily Dish] - 97%
Q12: MEDIA [ESPN] - 96%
Q12: MEDIA [Yahoo] - 97%

In [751]:
# drop columns
df = df.drop(['Q12: MEDIA [Yahoo]', 'Q12: MEDIA [ESPN]','Q12: MEDIA [Daily Dish]','Unnamed: 113', 
              'Q9: OTHER COMMENTS', 'Q8: DESPAIR OTHER', 'Q7: JOY OTHER' ], axis=1)

In [752]:
df.shape

(2460, 113)

In [753]:
# Check for duplicates in sample
print("Internal ID duplicated: {}".format(any(df['Internal ID'].duplicated())))

Internal ID duplicated: False

We will check which rows have the most missing data. If there are rows with more than 80% of the data missing, meaning if an observation is missing values from 91 columns out of 113, then we will remove those observations.

In [754]:
# check for missing value for Each observation
def percentMissing_row(df):
    index_num = []
    # % of missing data
    for i in range(len(df.index)):
        # create missing indicator for features with missing data
        missing = df.iloc[i].isnull().sum()   # checking null value for each observation
        pct_missing = (missing/113)*100
        if pct_missing >=80:
            print('row index {} - {}%'.format(i, round(pct_missing)))
            index_num.append(i)
    return index_num

In [755]:
index_list = percentMissing_row(df)

row index 0 - 99%
row index 2 - 96%
row index 6 - 95%
row index 10 - 96%
row index 18 - 95%
row index 19 - 95%
row index 24 - 95%
row index 25 - 95%
row index 30 - 95%
row index 35 - 95%
row index 36 - 99%
row index 38 - 95%
row index 40 - 95%
row index 42 - 96%
row index 47 - 95%
row index 48 - 95%
row index 55 - 95%
row index 61 - 95%
row index 62 - 95%
row index 66 - 95%
row index 67 - 95%
row index 76 - 95%
row index 78 - 95%
row index 84 - 96%
row index 86 - 96%
row index 88 - 95%
row index 96 - 95%
row index 100 - 99%
row index 114 - 97%
row index 117 - 95%
row index 119 - 95%
row index 121 - 97%
row index 122 - 95%
row index 127 - 95%
row index 130 - 96%
row index 137 - 95%
row index 138 - 95%
row index 139 - 95%
row index 143 - 95%
row index 144 - 95%
row index 146 - 95%
row index 149 - 97%
row index 152 - 95%
row index 154 - 95%
row index 155 - 95%
row index 156 - 95%
row index 158 - 95%
row index 162 - 95%
row index 163 - 95%
row index 175 - 95%
row index 177 - 95%
row index 182 - 95%
row index 185 - 95%
row index 187 - 99%
row index 189 - 96%
row index 191 - 95%
row index 192 - 95%
row index 201 - 95%
row index 208 - 95%
row index 213 - 95%
row index 214 - 95%
row index 216 - 95%
row index 228 - 95%
row index 230 - 96%
row index 232 - 95%
row index 235 - 95%
row index 236 - 92%
row index 237 - 95%
row index 239 - 95%
row index 240 - 95%
row index 241 - 95%
row index 242 - 96%
row index 251 - 95%
row index 257 - 95%
row index 259 - 95%
row index 271 - 95%
row index 272 - 95%
row index 274 - 95%
row index 277 - 95%
row index 280 - 96%
row index 284 - 95%
row index 290 - 95%
row index 291 - 95%
row index 293 - 95%
row index 294 - 95%
row index 295 - 95%
row index 297 - 95%
row index 298 - 95%
row index 299 - 95%
row index 301 - 95%
row index 302 - 95%
row index 304 - 95%
row index 305 - 95%
row index 312 - 95%
row index 315 - 95%
row index 319 - 95%
row index 321 - 95%
row index 323 - 95%
row index 329 - 95%
row index 333 - 96%
row index 337 - 95%
row index 342 - 95%
row index 354 - 95%
row index 356 - 95%
row index 359 - 95%
row index 362 - 95%
row index 364 - 95%
row index 366 - 95%
row index 368 - 95%
row index 373 - 96%
row index 376 - 95%
row index 378 - 95%
row index 379 - 95%
row index 380 - 95%
row index 381 - 95%
row index 390 - 96%
row index 391 - 95%
row index 393 - 95%
row index 394 - 95%
row index 396 - 95%
row index 397 - 95%
row index 403 - 95%
row index 405 - 96%
row index 410 - 95%
row index 416 - 95%
row index 431 - 95%
row index 439 - 95%
row index 440 - 95%
row index 442 - 95%
row index 447 - 95%
row index 449 - 95%
row index 456 - 95%
row index 467 - 95%
row index 478 - 95%
row index 480 - 96%
row index 483 - 95%
row index 490 - 95%
row index 495 - 95%
row index 496 - 95%
row index 499 - 95%
row index 502 - 95%
row index 504 - 96%
row index 505 - 95%
row index 512 - 95%
row index 521 - 95%
row index 523 - 95%
row index 527 - 96%
row index 528 - 95%
row index 532 - 96%
row index 540 - 96%
row index 542 - 95%
row index 546 - 99%
row index 554 - 95%
row index 555 - 95%
row index 557 - 95%
row index 558 - 95%
row index 562 - 96%
row index 567 - 95%
row index 569 - 95%
row index 578 - 95%
row index 584 - 95%
row index 586 - 95%
row index 588 - 95%
row index 597 - 95%
row index 604 - 95%
row index 608 - 95%
row index 609 - 95%
row index 620 - 95%
row index 621 - 95%
row index 626 - 95%
row index 627 - 95%
row index 632 - 95%
row index 634 - 95%
row index 635 - 95%
row index 644 - 99%
row index 651 - 96%
row index 655 - 95%
row index 656 - 97%
row index 678 - 95%
row index 679 - 96%
row index 681 - 95%
row index 690 - 95%
row index 692 - 95%
row index 693 - 99%
row index 698 - 95%
row index 700 - 95%
row index 704 - 98%
row index 707 - 95%
row index 708 - 98%
row index 711 - 95%
row index 714 - 95%
row index 715 - 96%
row index 716 - 95%
row index 717 - 95%
row index 719 - 96%
row index 725 - 95%
row index 727 - 95%
row index 729 - 95%
row index 732 - 95%
row index 734 - 99%
row index 735 - 96%
row index 738 - 96%
row index 742 - 95%
row index 748 - 95%
row index 759 - 97%
row index 761 - 95%
row index 769 - 88%
row index 779 - 95%
row index 785 - 96%
row index 786 - 95%
row index 787 - 95%
row index 792 - 95%
row index 795 - 95%
row index 798 - 95%
row index 802 - 95%
row index 808 - 95%
row index 812 - 95%
row index 816 - 95%
row index 818 - 95%
row index 819 - 95%
row index 820 - 95%
row index 825 - 95%
row index 830 - 95%
row index 838 - 99%
row index 839 - 95%
row index 844 - 95%
row index 845 - 98%
row index 846 - 95%
row index 857 - 95%
row index 859 - 95%
row index 860 - 95%
row index 861 - 95%
row index 862 - 95%
row index 865 - 95%
row index 869 - 97%
row index 870 - 81%
row index 871 - 95%
row index 872 - 95%
row index 873 - 95%
row index 876 - 95%
row index 878 - 95%
row index 890 - 95%
row index 895 - 95%
row index 905 - 95%
row index 909 - 95%
row index 915 - 95%
row index 916 - 95%
row index 917 - 95%
row index 924 - 95%
row index 931 - 93%
row index 937 - 95%
row index 942 - 95%
row index 946 - 95%
row index 948 - 95%
row index 949 - 95%
row index 952 - 95%
row index 953 - 84%
row index 957 - 96%
row index 958 - 95%
row index 968 - 95%
row index 969 - 95%
row index 971 - 95%
row index 974 - 95%
row index 989 - 95%
row index 991 - 95%
row index 992 - 95%
row index 996 - 96%
row index 997 - 95%
row index 1000 - 95%
row index 1004 - 99%
row index 1009 - 95%
row index 1014 - 98%
row index 1028 - 95%
row index 1033 - 95%
row index 1037 - 95%
row index 1040 - 95%
row index 1042 - 95%
row index 1047 - 95%
row index 1052 - 95%
row index 1057 - 95%
row index 1058 - 95%
row index 1066 - 95%
row index 1068 - 95%
row index 1076 - 99%
row index 1077 - 95%
row index 1083 - 95%
row index 1095 - 99%
row index 1102 - 95%
row index 1104 - 95%
row index 1109 - 95%
row index 1111 - 95%
row index 1119 - 95%
row index 1125 - 95%
row index 1127 - 95%
row index 1129 - 95%
row index 1145 - 95%
row index 1146 - 95%
row index 1147 - 95%
row index 1148 - 91%
row index 1149 - 93%
row index 1150 - 95%
row index 1153 - 95%
row index 1158 - 95%
row index 1159 - 95%
row index 1161 - 98%
row index 1163 - 95%
row index 1168 - 95%
row index 1172 - 95%
row index 1173 - 95%
row index 1177 - 95%
row index 1184 - 95%
row index 1199 - 95%
row index 1200 - 96%
row index 1201 - 95%
row index 1216 - 95%
row index 1218 - 96%
row index 1220 - 95%
row index 1225 - 95%
row index 1227 - 95%
row index 1232 - 95%
row index 1237 - 95%
row index 1239 - 95%
row index 1249 - 95%
row index 1253 - 95%
row index 1259 - 95%
row index 1267 - 95%
row index 1270 - 95%
row index 1271 - 95%
row index 1272 - 95%
row index 1278 - 95%
row index 1280 - 95%
row index 1285 - 95%
row index 1286 - 95%
row index 1295 - 99%
row index 1297 - 95%
row index 1302 - 95%
row index 1305 - 95%
row index 1312 - 95%
row index 1315 - 95%
row index 1321 - 95%
row index 1329 - 95%
row index 1335 - 95%
row index 1336 - 95%
row index 1341 - 96%
row index 1342 - 95%
row index 1345 - 99%
row index 1346 - 95%
row index 1350 - 95%
row index 1351 - 95%
row index 1357 - 95%
row index 1362 - 95%
row index 1368 - 95%
row index 1369 - 95%
row index 1373 - 95%
row index 1374 - 95%
row index 1376 - 96%
row index 1378 - 95%
row index 1382 - 95%
row index 1387 - 96%
row index 1398 - 95%
row index 1401 - 95%
row index 1402 - 95%
row index 1405 - 95%
row index 1407 - 95%
row index 1412 - 95%
row index 1415 - 95%
row index 1416 - 95%
row index 1417 - 95%
row index 1420 - 95%
row index 1422 - 95%
row index 1424 - 95%
row index 1426 - 95%
row index 1434 - 96%
row index 1440 - 95%
row index 1441 - 96%
row index 1445 - 95%
row index 1451 - 96%
row index 1452 - 97%
row index 1455 - 95%
row index 1459 - 95%
row index 1461 - 95%
row index 1462 - 95%
row index 1468 - 95%
row index 1472 - 95%
row index 1478 - 95%
row index 1480 - 95%
row index 1483 - 95%
row index 1490 - 95%
row index 1496 - 95%
row index 1499 - 95%
row index 1504 - 95%
row index 1510 - 99%
row index 1515 - 96%
row index 1516 - 95%
row index 1525 - 95%
row index 1534 - 95%
row index 1545 - 95%
row index 1547 - 95%
row index 1549 - 95%
row index 1550 - 95%
row index 1555 - 85%
row index 1557 - 95%
row index 1560 - 95%
row index 1566 - 95%
row index 1569 - 95%
row index 1570 - 95%
row index 1571 - 95%
row index 1575 - 95%
row index 1577 - 95%
row index 1580 - 95%
row index 1590 - 95%
row index 1599 - 99%
row index 1601 - 95%
row index 1603 - 95%
row index 1604 - 95%
row index 1609 - 97%
row index 1618 - 95%
row index 1619 - 95%
row index 1621 - 95%
row index 1622 - 95%
row index 1636 - 95%
row index 1639 - 95%
row index 1645 - 95%
row index 1649 - 95%
row index 1650 - 97%
row index 1652 - 96%
row index 1653 - 95%
row index 1655 - 95%
row index 1657 - 95%
row index 1661 - 95%
row index 1662 - 95%
row index 1665 - 95%
row index 1671 - 95%
row index 1674 - 95%
row index 1680 - 95%
row index 1685 - 95%
row index 1690 - 95%
row index 1699 - 95%
row index 1708 - 95%
row index 1709 - 95%
row index 1711 - 95%
row index 1721 - 95%
row index 1722 - 95%
row index 1724 - 95%
row index 1725 - 95%
row index 1736 - 95%
row index 1737 - 95%
row index 1748 - 95%
row index 1749 - 95%
row index 1752 - 95%
row index 1753 - 95%
row index 1758 - 95%
row index 1759 - 95%

row index 1770 - 95%
row index 1775 - 95%
row index 1777 - 95%
row index 1780 - 95%
row index 1781 - 95%
row index 1782 - 95%
row index 1788 - 95%
row index 1789 - 95%
row index 1791 - 96%
row index 1794 - 95%
row index 1796 - 95%
row index 1801 - 95%
row index 1803 - 95%
row index 1809 - 95%
row index 1816 - 95%
row index 1819 - 95%
row index 1821 - 95%
row index 1823 - 95%
row index 1827 - 95%
row index 1829 - 95%
row index 1836 - 95%
row index 1852 - 95%
row index 1854 - 95%
row index 1859 - 95%
row index 1861 - 95%
row index 1864 - 95%
row index 1868 - 95%
row index 1872 - 95%
row index 1873 - 95%
row index 1879 - 96%
row index 1881 - 95%
row index 1883 - 95%
row index 1884 - 95%
row index 1887 - 95%
row index 1891 - 95%
row index 1892 - 95%
row index 1895 - 99%
row index 1897 - 95%
row index 1900 - 97%
row index 1901 - 95%
row index 1902 - 95%
row index 1906 - 95%
row index 1908 - 95%
row index 1909 - 95%
row index 1913 - 95%
row index 1915 - 95%
row index 1917 - 95%
row index 1918 - 95%
row index 1923 - 95%
row index 1924 - 95%
row index 1926 - 95%
row index 1927 - 95%
row index 1937 - 95%
row index 1938 - 96%
row index 1939 - 95%
row index 1943 - 95%
row index 1953 - 95%
row index 1958 - 95%
row index 1959 - 96%
row index 1963 - 95%
row index 1972 - 99%
row index 1976 - 96%
row index 1977 - 97%
row index 1978 - 95%
row index 1983 - 95%
row index 1988 - 95%
row index 1991 - 95%
row index 2001 - 95%
row index 2003 - 95%
row index 2007 - 95%
row index 2008 - 95%
row index 2009 - 95%
row index 2012 - 95%
row index 2013 - 95%
row index 2015 - 95%
row index 2017 - 95%
row index 2018 - 95%
row index 2020 - 95%
row index 2023 - 95%
row index 2031 - 95%
row index 2032 - 95%
row index 2042 - 95%
row index 2047 - 95%
row index 2056 - 95%
row index 2057 - 96%
row index 2059 - 95%
row index 2060 - 95%
row index 2064 - 95%
row index 2075 - 95%
row index 2076 - 96%
row index 2078 - 95%
row index 2080 - 96%
row index 2081 - 95%
row index 2082 - 95%
row index 2083 - 95%
row index 2085 - 95%
row index 2086 - 95%
row index 2095 - 95%
row index 2098 - 95%
row index 2100 - 95%
row index 2111 - 95%
row index 2112 - 95%
row index 2117 - 95%
row index 2120 - 95%
row index 2122 - 95%
row index 2125 - 95%
row index 2126 - 95%
row index 2131 - 95%
row index 2132 - 95%
row index 2133 - 95%
row index 2147 - 96%
row index 2148 - 95%
row index 2151 - 95%
row index 2152 - 95%
row index 2154 - 95%
row index 2161 - 95%
row index 2162 - 95%
row index 2169 - 95%
row index 2176 - 95%
row index 2183 - 95%
row index 2184 - 96%
row index 2186 - 95%
row index 2187 - 95%
row index 2188 - 95%
row index 2190 - 95%
row index 2191 - 95%
row index 2194 - 95%
row index 2197 - 95%
row index 2207 - 95%
row index 2208 - 95%
row index 2209 - 95%
row index 2212 - 95%
row index 2216 - 95%
row index 2219 - 95%
row index 2224 - 95%
row index 2225 - 95%
row index 2227 - 95%
row index 2238 - 95%
row index 2239 - 96%
row index 2241 - 95%
row index 2244 - 95%
row index 2245 - 95%
row index 2251 - 95%
row index 2252 - 95%
row index 2253 - 95%
row index 2254 - 95%
row index 2258 - 95%
row index 2259 - 95%
row index 2260 - 95%
row index 2262 - 95%
row index 2264 - 95%
row index 2265 - 95%
row index 2268 - 95%
row index 2269 - 95%
row index 2270 - 96%
row index 2274 - 95%
row index 2277 - 95%
row index 2283 - 95%
row index 2289 - 95%
row index 2291 - 95%
row index 2292 - 95%
row index 2293 - 95%
row index 2296 - 95%
row index 2298 - 92%
row index 2303 - 95%
row index 2311 - 90%
row index 2312 - 95%
row index 2314 - 96%
row index 2316 - 99%
row index 2322 - 95%
row index 2323 - 95%
row index 2325 - 95%
row index 2332 - 95%
row index 2335 - 95%
row index 2336 - 95%
row index 2340 - 95%
row index 2349 - 95%
row index 2351 - 95%
row index 2352 - 99%
row index 2357 - 95%
row index 2362 - 95%
row index 2363 - 95%
row index 2364 - 95%
row index 2369 - 95%
row index 2374 - 95%
row index 2386 - 96%
row index 2388 - 95%
row index 2389 - 95%
row index 2393 - 95%
row index 2394 - 95%
row index 2397 - 95%
row index 2401 - 95%
row index 2404 - 95%
row index 2405 - 95%
row index 2408 - 95%
row index 2409 - 95%
row index 2415 - 95%
row index 2416 - 95%
row index 2417 - 95%
row index 2420 - 95%
row index 2425 - 95%
row index 2437 - 95%
row index 2440 - 99%
row index 2445 - 95%
row index 2446 - 96%
row index 2447 - 96%
row index 2448 - 95%
row index 2449 - 95%
row index 2450 - 98%
row index 2451 - 95%
row index 2458 - 95%

In [756]:
df = df.drop(index_list)

In [757]:
df.shape

(1796, 113)

In [758]:
df.describe()

        Internal ID  Q12: MEDIA [Science]
count  1.796000e+03                1358.0
mean   9.028000e+07                   1.0
std    7.236850e+03                   0.0
min    9.027282e+07                   1.0
25%    9.027520e+07                   1.0
50%    9.027768e+07                   1.0
75%    9.028217e+07                   1.0
max    9.031480e+07                   1.0

In [759]:
df['Q12: MEDIA [Science]']= df['Q12: MEDIA [Science]'].fillna(np.mean(df['Q12: MEDIA [Science]']))

In [760]:
percentMissing(df)

['Internal ID' 'Q12: MEDIA [Science]']
Internal ID - 0%
Q1: GOING OUT? - 3%
Q2: GENDER - 1%
Q3: AGE - 2%
Q4: COUNTRY - 1%
Q5: STATE, PROVINCE, COUNTY, ETC - 2%
Q6 | 100 Grand Bar - 5%
Q6 | Anonymous brown globs that come in black and orange wrappers	(a.k.a. Mary Janes) - 4%
Q6 | Any full-sized candy bar - 1%
Q6 | Black Jacks - 17%
Q6 | Bonkers (the candy) - 18%
Q6 | Bonkers (the board game) - 19%
Q6 | Bottle Caps - 6%
Q6 | Box'o'Raisins - 1%
Q6 | Broken glow stick - 2%
Q6 | Butterfinger - 1%
Q6 | Cadbury Creme Eggs - 1%
Q6 | Candy Corn - 1%
Q6 | Candy that is clearly just the stuff given out for free at restaurants - 2%
Q6 | Caramellos - 5%
Q6 | Cash, or other forms of legal tender - 1%
Q6 | Chardonnay - 4%
Q6 | Chick-o-Sticks (we donÃ•t know what that is) - 16%
Q6 | Chiclets - 3%
Q6 | Coffee Crisp - 11%
Q6 | Creepy Religious comics/Chick Tracts - 2%
Q6 | Dental paraphenalia - 2%
Q6 | Dots - 4%
Q6 | Dove Bars - 2%
Q6 | Fuzzy Peaches - 9%
Q6 | Generic Brand Acetaminophen - 4%
Q6 | Glow sticks - 2%
Q6 | Goo Goo Clusters - 12%
Q6 | Good N' Plenty - 4%
Q6 | Gum from baseball cards - 3%
Q6 | Gummy Bears straight up - 2%
Q6 | Hard Candy - 2%
Q6 | Healthy Fruit - 2%
Q6 | Heath Bar - 3%
Q6 | Hershey's Dark Chocolate - 1%
Q6 | HersheyÃ•s Milk Chocolate - 0%
Q6 | Hershey's Kisses - 1%
Q6 | Hugs (actual physical hugs) - 3%
Q6 | Jolly Rancher (bad flavor) - 2%
Q6 | Jolly Ranchers (good flavor) - 2%
Q6 | JoyJoy (Mit Iodine!) - 20%
Q6 | Junior Mints - 2%
Q6 | Senior Mints - 15%
Q6 | Kale smoothie - 4%
Q6 | Kinder Happy Hippo - 16%
Q6 | Kit Kat - 1%
Q6 | LaffyTaffy - 4%
Q6 | LemonHeads - 4%
Q6 | Licorice (not black) - 1%
Q6 | Licorice (yes black) - 1%
Q6 | Lindt Truffle - 3%
Q6 | Lollipops - 2%
Q6 | Mars - 3%
Q6 | Maynards - 20%
Q6 | Mike and Ike - 4%
Q6 | Milk Duds - 2%
Q6 | Milky Way - 1%
Q6 | Regular M&Ms - 1%
Q6 | Peanut M&MÃ•s - 1%
Q6 | Blue M&M's - 4%
Q6 | Red M&M's - 4%
Q6 | Green Party M&M's - 6%
Q6 | Independent M&M's - 8%
Q6 | Abstained from M&M'ing. - 15%
Q6 | Minibags of chips - 3%
Q6 | Mint Kisses - 6%
Q6 | Mint Juleps - 8%
Q6 | Mr. Goodbar - 4%
Q6 | Necco Wafers - 4%
Q6 | Nerds - 3%
Q6 | Nestle Crunch - 2%
Q6 | Now'n'Laters - 9%
Q6 | Peeps - 3%
Q6 | Pencils - 3%
Q6 | Pixy Stix - 3%
Q6 | Real Housewives of Orange County Season 9 Blue-Ray - 5%
Q6 | ReeseÃ•s Peanut Butter Cups - 1%
Q6 | Reese's Pieces - 2%
Q6 | Reggie Jackson Bar - 19%
Q6 | Rolos - 3%
Q6 | Sandwich-sized bags filled with BooBerry Crunch - 6%
Q6 | Skittles - 2%
Q6 | Smarties (American) - 3%
Q6 | Smarties (Commonwealth) - 13%
Q6 | Snickers - 2%
Q6 | Sourpatch Kids (i.e. abominations of nature) - 4%
Q6 | Spotted Dick - 12%
Q6 | Starburst - 2%
Q6 | Sweet Tarts - 3%
Q6 | Swedish Fish - 3%
Q6 | Sweetums (a friend to diabetes) - 19%
Q6 | Take 5 - 14%
Q6 | Tic Tacs - 3%
Q6 | Those odd marshmallow circus peanut things - 4%
Q6 | Three Musketeers - 3%
Q6 | Tolberone something or other - 2%
Q6 | Trail Mix - 2%
Q6 | Twix - 2%
Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein - 7%
Q6 | Vicodin - 7%
Q6 | Whatchamacallit Bars - 9%
Q6 | White Bread - 5%
Q6 | Whole Wheat anything - 5%
Q6 | York Peppermint Patties - 2%
Q10: DRESS - 5%
Q11: DAY - 4%
Q12: MEDIA [Science] - 0%
Click Coordinates (x, y) - 11%

In [761]:
df.describe(include=['O'])

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q6 | Twix,"Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein",Q6 | Vicodin,Q6 | Whatchamacallit Bars,Q6 | White Bread,Q6 | Whole Wheat anything,Q6 | York Peppermint Patties,Q10: DRESS,Q11: DAY,"Click Coordinates (x, y)"
count,1734,1786,1761,1775,1755,1709,1722,1784,1499,1467,...,1768,1668,1671,1637,1703,1713,1753,1711,1731,1601
unique,2,4,98,100,431,3,3,3,3,3,...,3,3,3,3,3,3,3,2,2,951
top,No,Male,37,USA,California,JOY,DESPAIR,JOY,DESPAIR,MEH,...,JOY,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,White and gold,Friday,"(77, 24)"
freq,1497,1082,66,534,108,870,1086,1556,792,856,...,1411,1146,723,840,1455,1289,1103,1077,1090,9

Further using dropna so I can use other methods

In [762]:
df = df.dropna()
df.shape

(847, 113)

**2. Fuzzy Matching for Replacing values**

In [827]:

unique = df['Q4: COUNTRY'].unique().tolist()
sorted(unique)

score = [(x,) + i 
         for x in unique 
         for i in process.extract(x, unique, scorer=fuzz.token_sort_ratio)]
    
#Create a dataframe from the tuples
similarity = pd.DataFrame(score, columns=['Q4: COUNTRY','match','score'])

# because this will have repitative pairs, we will remove duplicated pairs from this
similarity['sorted_Q4: COUNTRY'] = np.minimum(similarity['Q4: COUNTRY'], similarity['match'])

In [828]:
def token_high(df, percent):
    
    # create a subset dataframe with higher percent match values
    high_score = df[(df['score'] >= percent) &
                                  (df['Q4: COUNTRY'] !=  df['match']) &
                                  (df['sorted_Q4: COUNTRY'] != df['match'])]
    
    # Drop the representative value column
    high_score = high_score.drop('sorted_Q4: COUNTRY',axis=1).copy()
    
    return high_score

In [829]:
high_score = token_high(similarity,5)
high_score

             Q4: COUNTRY                           match  score
2                    USA                           spain     50
6                 Canada                        Scotland     57
7                 Canada                          Narnia     50
8                 Canada                         Ireland     46
9                 Canada                         endland     46
12                Mexico                        Scotland     29
13                Mexico                           spain     18
16                    UK                             USA     40
19                    UK  subscribe to dm4uz3 on youtube      6
26                     A                             USA     50
27                     A                           Japan     33
28                     A                           spain     33
29                     A                          Canada     29
31               Ireland                         endland     71
32               Ireland                     Netherlands     56
33               Ireland                        Scotland     53
39              Scotland                         endland     53
41               Denmark                          Narnia     46
42               Denmark                         Germany     43
43               Denmark                         endland     43
46               France                          Ireland     46
47               France                          Germany     46
48               France                            Japan     36
49               France                            spain     36
51                 Japan                           spain     60
57               Germany                     Netherlands     44
58               Germany                         Ireland     43
62           Netherlands                         endland     56
63           Netherlands                        Scotland     53
71              Atlantis                     Netherlands     53
72              Atlantis                        Scotland     50
73              Atlantis                           Japan     46
74              Atlantis                 insanity lately     43
82                Narnia                 insanity lately     48
84                Narnia                         endland     46
91  I don't know anymore  subscribe to dm4uz3 on youtube     40
92  I don't know anymore                          Mexico     31
93  I don't know anymore                          Narnia     31

In [799]:
# create dictionary
match_dict = dict(zip(high_score['Q4: COUNTRY'], high_score.match))
len(match_dict)

11

In [767]:
del match_dict['Canada']

In [800]:
del match_dict['Ireland']

In [801]:
del match_dict['Can']
del match_dict['Mexico']
del match_dict['Narnia']
del match_dict['Japan']

match_dict

{'united states': 'united states of america',
 'US of A': 'u s a',
 'California': 'Narnia',
 'Ahem....Amerca': 'america',
 'u s a': 'u.s.',
 'USA USA USA!!!!': 'u s a'}

In [816]:
df['Q4: COUNTRY'].replace({'USA USA USA!!!!': 'USA', 'america': 'USA'}, inplace=True)

In [802]:
for key, value in match_dict.items():
    match_dict[key] = 'USA'

In [808]:
df['Q4: COUNTRY'].replace({'Can': 'Canada'}, inplace=True)

In [804]:
df['Q4: COUNTRY'].replace(match_dict, inplace=True)

In [793]:
df['Q4: COUNTRY'].replace({'usa': 'USA'}, inplace=True)
df['Q4: COUNTRY'].replace({'america': 'USA'}, inplace=True)
df['Q4: COUNTRY'].replace({'united states of america': 'USA'}, inplace=True)
df['Q4: COUNTRY'].replace({'murrika': 'USA'}, inplace=True)
df['Q4: COUNTRY'].replace({'usa': 'USA'}, inplace=True)
df['Q4: COUNTRY'].replace({'United Kingdom': 'UK'}, inplace=True)
df['Q4: COUNTRY'].replace({'u.s.': 'USA'}, inplace=True)
df['Q4: COUNTRY'].replace({'USA? Hard to tell anymore..': 'USA'}, inplace=True)
df['Q4: COUNTRY'].replace({'North Carolina': 'USA'}, inplace=True)
df['Q4: COUNTRY'].replace({'I pretend to be from Canada, but I am really from the United States.': 'USA'}, inplace=True)

**3. String Manipulation**

In [830]:
def no_whitespace(string):
    return string.strip()

# stripping white space from all column type as object
def clean_string(df):
    
    for col in df.columns:
        for i, row in df.iterrows():
            if df.at[i, col] == np.object:
                df.at[i, col] = no_whitespace(df.at[i, col])
    return df

df = clean_string(df)

**4. Hierarchical Indexing**

In [831]:
df.index

Int64Index([   1,    3,    8,   14,   16,   17,   27,   29,   31,   32,
            ...
            2430, 2432, 2435, 2439, 2441, 2443, 2452, 2454, 2457, 2459],
           dtype='int64', length=844)

In [832]:
df = df.set_index(['Q6 | Any full-sized candy bar','Internal ID'])
df.head()

                                          Q1: GOING OUT?          Q2: GENDER  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                No                Male
                              90272840                No                Male
                              90272858                No                Male
                              90272868                No              Female
                              90272880                No  I'd rather not say

                                          Q3: AGE Q4: COUNTRY  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821         44         USA
                              90272840         40         USA
                              90272858         40      Canada
                              90272868         37      Canada
                              90272880         59         USA

                                          Q5: STATE, PROVINCE, COUNTY, ETC  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                                  NM
                              90272840                                  or
                              90272858                             Ontario
                              90272868                             Ontario
                              90272880                            NEW YORK

                                          Q6 | 100 Grand Bar  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                   MEH
                              90272840                   MEH
                              90272858                   JOY
                              90272868                   MEH
                              90272880                   JOY

                                          Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                                               DESPAIR
                              90272840                                               DESPAIR
                              90272858                                               DESPAIR
                              90272868                                                   JOY
                              90272880                                                   MEH

                                          Q6 | Black Jacks  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                 MEH
                              90272840                 MEH
                              90272858                 MEH
                              90272868                 MEH
                              90272880                 JOY

                                          Q6 | Bonkers (the candy)  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                     DESPAIR
                              90272840                         MEH
                              90272858                         MEH
                              90272868                         JOY
                              90272880                         MEH

                                          Q6 | Bonkers (the board game)  ...  \
Q6 | Any full-sized candy bar Internal ID                                ...
JOY                           90272821                          DESPAIR  ...
                              90272840                          DESPAIR  ...
                              90272858                              MEH  ...
                              90272868                          DESPAIR  ...
                              90272880                              MEH  ...

                                          Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                                               DESPAIR
                              90272840                                               DESPAIR
                              90272858                                                   MEH
                              90272868                                               DESPAIR
                              90272880                                               DESPAIR

                                          Q6 | Vicodin  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821         DESPAIR
                              90272840             JOY
                              90272858         DESPAIR
                              90272868             MEH
                              90272880         DESPAIR

                                          Q6 | Whatchamacallit Bars  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                      DESPAIR
                              90272840                          JOY
                              90272858                          MEH
                              90272868                          JOY
                              90272880                          MEH

                                          Q6 | White Bread  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821             DESPAIR
                              90272840             DESPAIR
                              90272858             DESPAIR
                              90272868             DESPAIR
                              90272880             DESPAIR

                                          Q6 | Whole Wheat anything  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                      DESPAIR
                              90272840                      DESPAIR
                              90272858                      DESPAIR
                              90272868                      DESPAIR
                              90272880                      DESPAIR

                                          Q6 | York Peppermint Patties  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                         DESPAIR
                              90272840                         DESPAIR
                              90272858                         DESPAIR
                              90272868                             JOY
                              90272880                             MEH

                                               Q10: DRESS Q11: DAY  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821     White and gold   Sunday
                              90272840     White and gold   Sunday
                              90272858     Blue and black   Sunday
                              90272868     Blue and black   Sunday
                              90272880     Blue and black   Sunday

                                          Q12: MEDIA [Science]  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                     1.0
                              90272840                     1.0
                              90272858                     1.0
                              90272868                     1.0
                              90272880                     1.0

                                          Click Coordinates (x, y)
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                    (84, 25)
                              90272840                    (75, 23)
                              90272858                    (76, 24)
                              90272868                    (75, 25)
                              90272880                     (79, 5)

[5 rows x 111 columns]

**5. Merging Datasets**

Splitting data set into two dataset

In [833]:
df1 = df.drop(['Q1: GOING OUT?', 'Q5: STATE, PROVINCE, COUNTY, ETC','Q6 | Black Jacks', 'Q6 | Whatchamacallit Bars'], axis=1)
df2 = df[['Q1: GOING OUT?', 'Q5: STATE, PROVINCE, COUNTY, ETC','Q6 | Black Jacks', 'Q6 | Whatchamacallit Bars']]

In [834]:
new_df = pd.merge(df1,df2, right_index=True, left_on=['Q6 | Any full-sized candy bar', 'Internal ID'])

In [835]:
new_df.shape

(844, 111)

**6. Grouping by Function**

In [836]:
group = new_df.groupby('Q2: GENDER')['Q6 | Bonkers (the board game)'].value_counts()

In [837]:
group

Q2: GENDER          Q6 | Bonkers (the board game)
Female              MEH                              151
                    DESPAIR                          103
                    JOY                               42
I'd rather not say  MEH                               16
                    DESPAIR                            8
                    JOY                                1
Male                MEH                              265
                    DESPAIR                          192
                    JOY                               57
Other               DESPAIR                            4
                    MEH                                4
                    JOY                                1
Name: Q6 | Bonkers (the board game), dtype: int64

In [838]:
new_df['Q4: COUNTRY'].replace({'I pretend to be from Canada, but I am really from the United States.': 'USA'}, inplace=True)
new_df['Q4: COUNTRY'].replace({'USA? Hard to tell anymore.': 'USA'}, inplace=True)

**7. Cross Tabs**

In [839]:
pd.crosstab(new_df['Q4: COUNTRY'], new_df['Q2: GENDER'], margins=True)

Q2: GENDER                      Female  I'd rather not say  Male  Other  All
Q4: COUNTRY
A                                    0                   1     0      0    1
Atlantis                             0                   1     0      0    1
Canada                              29                   4    38      1   72
Denmark                              1                   0     0      0    1
France                               0                   0     1      0    1
Germany                              1                   0     0      0    1
I don't know anymore                 0                   0     1      0    1
Ireland                              2                   0     0      0    2
Japan                                1                   0     1      0    2
Mexico                               0                   0     2      0    2
Narnia                               0                   0     1      0    1
Netherlands                          0                   0     1      0    1
Scotland                             2                   0     0      0    2
UK                                   2                   0     5      0    7
USA                                257                  19   462      7  745
endland                              1                   0     0      0    1
insanity lately                      0                   0     0      1    1
spain                                0                   0     1      0    1
subscribe to dm4uz3 on youtube       0                   0     1      0    1
All                                296                  25   514      9  844

**8. Convert between string and date time**

In 2017 data there is no date time only day. So I will be adding a column for timestamp. Since data was released on October 25th @ 1:45 pm PST. I will use this date

In [842]:
from pandas.tseries.offsets import Day, MonthEnd
from datetime import datetime
import pytz

In [852]:
TimeStamp = []

In [853]:
for i, row in df.iterrows():
    x = datetime(2017,10,25,13,45)
    TimeStamp.append(str(x))

In [855]:
new_df['TimeStamp'] = TimeStamp

In [861]:
new_df.head()

                                                   Q2: GENDER Q3: AGE  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                   Male      44
                              90272840                   Male      40
                              90272858                   Male      40
                              90272868                 Female      37
                              90272880     I'd rather not say      59

                                          Q4: COUNTRY Q6 | 100 Grand Bar  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821            USA                MEH
                              90272840            USA                MEH
                              90272858         Canada                JOY
                              90272868         Canada                MEH
                              90272880            USA                JOY

                                          Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                                               DESPAIR
                              90272840                                               DESPAIR
                              90272858                                               DESPAIR
                              90272868                                                   JOY
                              90272880                                                   MEH

                                          Q6 | Bonkers (the candy)  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                     DESPAIR
                              90272840                         MEH
                              90272858                         MEH
                              90272868                         JOY
                              90272880                         MEH

                                          Q6 | Bonkers (the board game)  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                          DESPAIR
                              90272840                          DESPAIR
                              90272858                              MEH
                              90272868                          DESPAIR
                              90272880                              MEH

                                          Q6 | Bottle Caps Q6 | Box'o'Raisins  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821             DESPAIR            DESPAIR
                              90272840                 MEH            DESPAIR
                              90272858                 MEH            DESPAIR
                              90272868                 MEH            DESPAIR
                              90272880             DESPAIR                MEH

                                          Q6 | Broken glow stick  ...  \
Q6 | Any full-sized candy bar Internal ID                         ...
JOY                           90272821                   DESPAIR  ...
                              90272840                   DESPAIR  ...
                              90272858                   DESPAIR  ...
                              90272868                   DESPAIR  ...
                              90272880                   DESPAIR  ...

                                          Q6 | York Peppermint Patties  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                         DESPAIR
                              90272840                         DESPAIR
                              90272858                         DESPAIR
                              90272868                             JOY
                              90272880                             MEH

                                               Q10: DRESS Q11: DAY  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821     White and gold   Sunday
                              90272840     White and gold   Sunday
                              90272858     Blue and black   Sunday
                              90272868     Blue and black   Sunday
                              90272880     Blue and black   Sunday

                                          Q12: MEDIA [Science]  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                     1.0
                              90272840                     1.0
                              90272858                     1.0
                              90272868                     1.0
                              90272880                     1.0

                                          Click Coordinates (x, y)  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                    (84, 25)
                              90272840                    (75, 23)
                              90272858                    (76, 24)
                              90272868                    (75, 25)
                              90272880                     (79, 5)

                                          Q1: GOING OUT?  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                No
                              90272840                No
                              90272858                No
                              90272868                No
                              90272880                No

                                          Q5: STATE, PROVINCE, COUNTY, ETC  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                                  NM
                              90272840                                  or
                              90272858                             Ontario
                              90272868                             Ontario
                              90272880                            NEW YORK

                                          Q6 | Black Jacks  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                 MEH
                              90272840                 MEH
                              90272858                 MEH
                              90272868                 MEH
                              90272880                 JOY

                                          Q6 | Whatchamacallit Bars  \
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821                      DESPAIR
                              90272840                          JOY
                              90272858                          MEH
                              90272868                          JOY
                              90272880                          MEH

                                                     TimeStamp
Q6 | Any full-sized candy bar Internal ID
JOY                           90272821     2017-10-25 13:45:00
                              90272840     2017-10-25 13:45:00
                              90272858     2017-10-25 13:45:00
                              90272868     2017-10-25 13:45:00
                              90272880     2017-10-25 13:45:00

[5 rows x 112 columns]